<template><div><h1 id="社群节点迁移气泡图可视设计方法" tabindex="-1"><a class="header-anchor" href="#社群节点迁移气泡图可视设计方法" aria-hidden="true">#</a> 社群节点迁移气泡图可视设计方法</h1>
<p>本组件主要用于呈现不同类别中节点数量的变化情况。</p>
<p>组件结构</p>
<p><strong>Demo</strong>：http://localhost:8080/</p>
<h2 id="输入数据" tabindex="-1"><a class="header-anchor" href="#输入数据" aria-hidden="true">#</a> 输入数据</h2>
<ul>
<li>描述：需要观察类型中节点数量变化情况的数据。</li>
<li>类型：<code v-pre>Array</code>，需要满足json格式。</li>
</ul>
<p>每条数据中需要包含以下内容：</p>
<ol>
<li>node：是某个ip地址，例如192.168.1.1，是string类型。</li>
<li>time：时间。string类型，格式为“2023-10-06 11:00”。</li>
<li>type：种类名词，string类型。</li>
</ol>
<h2 id="如何使用" tabindex="-1"><a class="header-anchor" href="#如何使用" aria-hidden="true">#</a> 如何使用</h2>
<h3 id="启动" tabindex="-1"><a class="header-anchor" href="#启动" aria-hidden="true">#</a> 启动</h3>
<div class="language-c line-numbers-mode" data-ext="c"><pre v-pre class="language-c"><code><span class="token comment">// component来自BubbleChartView.vue</span>
component<span class="token punctuation">.</span><span class="token function">drawBubbleChart</span><span class="token punctuation">(</span>data<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="交互" tabindex="-1"><a class="header-anchor" href="#交互" aria-hidden="true">#</a> 交互</h3>
<p>在该组件上，存在以下交互：</p>
<ul>
<li><strong>类别选择</strong>：在视图最左侧会垂直显示所有类别，并配以不同颜色的方块。选择某个类别，会展示相对于该类别其他类别的迁入迁出情况和其数量变化的绝对值。</li>
</ul>
<h2 id="外部接口" tabindex="-1"><a class="header-anchor" href="#外部接口" aria-hidden="true">#</a> 外部接口</h2>
<h3 id="发送" tabindex="-1"><a class="header-anchor" href="#发送" aria-hidden="true">#</a> 发送</h3>
<p>暂无接口</p>
<p><strong>接收</strong></p>
<p>暂无接口</p>
<h2 id="使用示例" tabindex="-1"><a class="header-anchor" href="#使用示例" aria-hidden="true">#</a> 使用示例</h2>
<div class="language-c line-numbers-mode" data-ext="c"><pre v-pre class="language-c"><code><span class="token punctuation">[</span>
   <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.1"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 10:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"1"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
   <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.2"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 10:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"2"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
   <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.3"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 10:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"1"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
   <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.4"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 10:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"4"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
   <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.5"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 10:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"5"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>

   <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.1"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 11:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"1"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
   <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.2"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 11:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"1"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
   <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.3"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 11:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"2"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
   <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.4"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 11:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"5"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
   <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.5"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 11:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"4"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>

   <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.1"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 12:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"5"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
   <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.2"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 12:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"4"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
   <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.3"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 12:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"3"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
   <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.4"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 12:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"2"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
   <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.5"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 12:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"1"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>

    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.1"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 13:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"5"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.2"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 13:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"5"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.3"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 13:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"5"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.4"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 13:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"2"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.5"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 13:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"2"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>

    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.1"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 14:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"3"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.2"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 14:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"2"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.3"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 14:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"1"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.4"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 14:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"4"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.5"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 14:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"5"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>

    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.1"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 15:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"4"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.2"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 15:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"4"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.3"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 15:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"3"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.4"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 15:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"5"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.5"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 15:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"1"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>

    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.1"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 16:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"5"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.2"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 16:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"1"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.3"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 16:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"2"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.4"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 16:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"4"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.5"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 16:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"5"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>

    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.1"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 17:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"4"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.2"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 17:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"3"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.3"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 17:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"2"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.4"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 17:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"2"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.5"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 17:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"4"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>

    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.1"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 18:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"2"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.2"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 18:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"5"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.3"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 18:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"4"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.4"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 18:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"1"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.5"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 18:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"3"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>

    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.1"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 19:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"1"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.2"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 19:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"2"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.3"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 19:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"3"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.4"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 19:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"4"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.5"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 19:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"5"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>

    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.1"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 20:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"1"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.2"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 20:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"2"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.3"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 20:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"3"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.4"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 20:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"4"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.5"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 20:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"5"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>

    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.1"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 21:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"1"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.2"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 21:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"2"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.3"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 21:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"3"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.4"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 21:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"4"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span> node<span class="token operator">:</span> <span class="token string">"192.168.1.5"</span><span class="token punctuation">,</span> time<span class="token operator">:</span> <span class="token string">"2020-19-20 21:00"</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">"5"</span> <span class="token punctuation">}</span>
<span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然后开始绘图：</p>
<div class="language-c line-numbers-mode" data-ext="c"><pre v-pre class="language-c"><code><span class="token keyword">const</span> component <span class="token operator">=</span> this<span class="token punctuation">.</span>$ref<span class="token punctuation">[</span><span class="token char">'BubbleChartView'</span><span class="token punctuation">]</span> <span class="token comment">//这里的component指的是组件BubbleChartView.vue的vue实例，采取合理的方法获取即可</span>
component<span class="token punctuation">.</span><span class="token function">drawBubbleChart</span><span class="token punctuation">(</span>data<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>绘图效果如下所示：</p>
<p><img src="https://drive.google.com/uc?export=view&amp;id=10H_brJGtmVVhEmvlA_SujB0tKqElQBt6" alt="image"></p>
<h2 id="引用" tabindex="-1"><a class="header-anchor" href="#引用" aria-hidden="true">#</a> 引用</h2>
<p>[1] Jiazhi Xia, Yuhong Zhang, Hui Ye, et al. SuPoolVisor: a visual analytics system for mining pool surveillance.[J]. Frontiers of Information Technology &amp; Electronic Engineering, 2020, 21(4):507-523, https://doi.org/10.1631/FITEE.1900532.</p>
</div></template>


